### ISSUE TITLE
Working directory when running tests is VS Code

### ISSUE THREAD

**Issue by korbinian90** [julia-vscode/TestItemRunner.jl#28]
The working directory when running a @testset via the vs code UI is "C:\\Users\\korbi\\AppData\\Local\\Programs\\Microsoft VS Code".
The default julia package test runs in "test" inside the package being tested.

This makes it complicated to reference data in the repository used for testing purposes.
If the path working directory would be identical, @testset could simply be replaced with @testitem.

Otherwise, this is an amazing feature! The tests run instantly!

**Comment by korbinian90** [comment]
Solved this for now for my use case:
```julia
@testitem "test" begin
cd(@__DIR__)
load_data("data/small")
...
```

You can keep this open or close it as you prefer ;)

**Comment by davidanthoff** [comment]
I think this is now properly fixed.
