### ISSUE TITLE
Bug: Module docstring breaks detection of tests

### ISSUE THREAD

**Issue by jakobnissen** [julia-vscode/TestItemRunner.jl#33]
In the following MWE package:
```julia
module Foo

using TestItems

greet() = print("Hello World!")

@testitem "Test1" begin
    @test 1 + 1 == 2
end

end # module Foo
```

With the recommended `test/runtests.jl`:
```julia
using TestItemRunner

@run_package_tests
```

TestItemRunner runs well: 
```
Test Summary: | Pass  Total  Time
Package       |    1      1  0.1s
     Testing Foo tests passed
```

However, adding a docstring at the top of the module:
```julia
"Foo"
module Foo
[ test of file elided ]
```
Makes this package detect zero tests:
```
Test Summary: |Time
Package       | None  0.0s
     Testing Foo tests passed
```

**Comment by jakobnissen** [comment]
Detection of `@testitem` is not tested. I recommend that

**Comment by davidanthoff** [comment]
Fixed in https://github.com/julia-vscode/TestItemDetection.jl/pull/21, tests in https://github.com/julia-vscode/JuliaWorkspaces.jl/pull/22.
