### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by binnisb** [julia-vscode/TestItemRunner.jl#34]
I guess this is on your roadmap but it would be nice to be able to debug the tests.

**Comment by blolt** [comment]
Hey can I pick this up? The workflow for debugging Julia in VS code is a bit of a mess right now, especially for large end-to-end tests. Not sure if any work has been done on the matter.

**Comment by davidanthoff** [comment]
There is a PR over on the Julia VS Code repo where I rewrote much of the debugger integration for the extension, and that PR also adds support for debugging test items. Please give it a try, feedback is super useful at this stage.

**Comment by blolt** [comment]
Will check it out, thanks!

**Comment by blolt** [comment]
https://github.com/julia-vscode/julia-vscode/issues/3616

Just posting the issue here for documentation. Will see about giving some feedback today or tomorrow.

**Comment by davidanthoff** [comment]
This is now implemented in the preview version of the extension.
