### ISSUE TITLE
Release a new version 

### ISSUE THREAD

**Issue by tz-lom** [julia-vscode/TestItemRunner.jl#46]
v0.2.1 was released 7 month ago
I see several features were added to the master after that.
Given repo is a WIP maybe it's a good time to release a new version and consider more frequent releases in a future?

**Comment by gdalle** [comment]
I agree, I would love to have the `verbose=true` option for package tests!

**Comment by davidanthoff** [comment]
Ah, I should remove the WIP badge, in my mind this is all ready to be used (and it is widely used).

Some of the features that we added to `main` are not ready to be used in general, in particular the `@testsetup` stuff is not yet supported in the VS Code extension and I want to finish the implementation over there before making it fully "public".

The `verbose` thing is the only other thing. I guess we could tag a release and just not mention the `@testsetup` things...

I should add that I've also been working on https://github.com/julia-vscode/TestItemRunner2.jl that has a lot more features, including parallel test execution etc.

**Comment by gdalle** [comment]
I trust your judgement @davidanthoff!

By the way, do you think https://github.com/julia-vscode/julia-vscode/issues/3288 is an issue for julia-vscode or TestItemRunner(2).jl?

**Comment by gdalle** [comment]
On second thought, a release with the verbose mode would really be crucial for those who don't develop with VSCode but still want a detailed test summary!

**Comment by gdalle** [comment]
Hez @davidanthoff, just a friendly ping about this new version, the verbose behavior is (I think) really crucial for widespread adoption

**Comment by davidanthoff** [comment]
https://github.com/JuliaRegistries/General/pull/85686

**Comment by gdalle** [comment]
Thank you!
