### ISSUE TITLE
Add support for the `setup` argument as in the `ReTestItems`

### ISSUE THREAD

**Issue by bvdmitri** [julia-vscode/TestItemRunner.jl#56]
[ReTestItems](https://github.com/JuliaTesting/ReTestItems.jl) package is compatible with VSCode UI, but additionally exposes the `setup` keyword argument, which is currently ignored by VSCode test running infrastructure. It would be nice to synchronise here a bit, since setting up common functionality/fixtures in tests is extremely useful. For now, if some wants to use `ReTestItems` both in VSCode and in REPL, they need to avoid the `setup` argument and use `include` instead. 

I see there was some discussion [here](https://github.com/julia-vscode/TestItemRunner.jl/pull/39#issuecomment-1428346527), but it looks like this functionality is still not available in the VSCode?

**Comment by davidanthoff** [comment]
Already tracked in https://github.com/julia-vscode/TestItemRunner.jl/issues/11, duplicate.
