### ISSUE TITLE
Can't run the tests from VS Code

### ISSUE THREAD

**Issue by coderguy57** [julia-vscode/TestItemRunner.jl#58]
I can run it from the terminal, but whenever I run it from the VS Code I get the following error:

"Unable to identify a Julia package for this test item."

This is the code I run
```julia
using TestItems, TestItemRunner

@testitem "Test" begin
    @test 1 + 1 == 2
end

@run_package_tests
```

**Comment by kbarros** [comment]
Perhaps its unrelated, but I was seeing a lot of confusing behaviors when the `Julia env:` toggle at the bottom of the VSCode window was misconfigured. Worth a check? https://github.com/julia-vscode/TestItemRunner.jl/issues/67

**Comment by davidanthoff** [comment]
Closing as this would need more info to diagnose.
