### ISSUE TITLE
Do not run tests on files not included (?)

### ISSUE THREAD

**Issue by lmiq** [julia-vscode/TestItemRunner.jl#60]
I may be doing something wrong, by in my project I have something like:

```julia
module MyPkg
    using TestItems
    include("somefile.jl")
end
```
Inside `somefile.jl` there are some tests defined by `@testitem` sets. 

It seems that, if I comment the line that includes `somefile.jl`, the tests inside `somefile.jl` are stil checked up, and the tests break if there are syntax errors in that file. 

Is this expected?

**Comment by davidanthoff** [comment]
Yes, test items are detected syntactically, they can just appear in any file anywhere.
