### ISSUE TITLE
Confusing failure when the `Julia env:` toggle is modified

### ISSUE THREAD

**Issue by kbarros** [julia-vscode/TestItemRunner.jl#67]
TestItemRunner is so crucial to my workflow that I almost can't function without it anymore 😄 

This happened to me when I accidentally switched the `Julia env:` toggle at the bottom of the VSCode window. After doing so, test items still appear on the `Testing` panel on the left, even when the VSCode application is restarted. However, attempting to run any test would fail at the step of launching the Julia test process. This launch simply hangs, with no error message to explain what's going on. This caused me a lot of confusion.

Can VSCode report an error message explaining that the Julia environment is misconfigured for the currently opened project?

**Comment by davidanthoff** [comment]
Can you try this again from the preview version of the extension? I think I fixed this, but would be good to confirm. I'll close this issue for now, but please reopen if this still doesn't work.
