### ISSUE TITLE
Debugging and TestItemRunner

### ISSUE THREAD

**Issue by feribg** [julia-vscode/TestItemRunner.jl#68]
Here's a more detailed thread, but I cant seem to find a way to debug either individual tests or the entire `runtests.jl` file. Also clicking debug test from the VSCode UI does nothing, the test run is gray and seemingly skipped. Whats the recommended way to debug unit tests ?

https://discourse.julialang.org/t/unit-tests-debugger-vscode/113419/3

**Comment by davidanthoff** [comment]
The VS Code preview version of the extension now has support for debugging of test items. Please give it a try, and if you run into errors or bugs please open new issues here.
