### ISSUE TITLE
TestItemRunner process doesn't restart after deps added to test env and can't manually stop process

### ISSUE THREAD

**Issue by ianfiske** [julia-vscode/TestItemRunner.jl#69]
I have experienced the following issue a couple of times.

- I add a new dependency to the `test` environment that is used in one or more `@testitem`s. 
- I re-run the tests.  This probably should require a restart of the test process.
 
However, instead it runs and throws an error about the new dependency being missing.  I have tried the manual VSCode command `Julia: Stop Test Process` to manually trigger a restart of the test process, but this throws a VSCode error:

<img width="249" alt="image" src="https://github.com/julia-vscode/TestItemRunner.jl/assets/135570/e5883aee-df64-4e20-9787-ce738c16bbe3">

**Comment by davidanthoff** [comment]
Yep, that is a bug, or rather a not-yet-implemented feature... I'm already tracking this over at https://github.com/julia-vscode/julia-vscode/issues/3022, so closing here.
