### ISSUE TITLE
Document `@testsetup`

### ISSUE THREAD

**Issue by MilesCranmer** [julia-vscode/TestItemRunner.jl#71]
I noticed from the tests there is this `@testsetup` which is very useful for my work:

https://github.com/julia-vscode/TestItemRunner.jl/blob/main/test/runtests.jl

Would be good to have documentation on this as I am curious about the entire API and any caveats to be aware of.

**Comment by davidanthoff** [comment]
That doesn't work yet, though :) I've just started the implementation, but it is not yet done.

**Comment by MilesCranmer** [comment]
Oh I see, thanks for clarifying
