### ISSUE TITLE
Fails on Julia 1.11-beta due to broken TestEnv

### ISSUE THREAD

**Issue by kbarros** [julia-vscode/TestItemRunner.jl#72]
In Julia 1.11-beta, the interface for `Pkg.Operations: sandbox` has changed, which breaks TestEnv, which in turn breaks TestItemRunner.

The problem is documented in this issue: https://github.com/JuliaTesting/TestEnv.jl/issues/86

Possible fix in this PR: https://github.com/JuliaTesting/TestEnv.jl/pull/87.

**Comment by kbarros** [comment]
Now that https://github.com/JuliaTesting/TestEnv.jl/pull/87 merged, how can one go about pointing TestItemRunner to the latest TestEnv dependency? (It looks like it might be something internal to the VSCode packages, not in the user's Julia environment?)

**Comment by davidanthoff** [comment]
I'm updating the extension right now
