### ISSUE TITLE
Adding common code lines/expressions to `@run_package_tests`

### ISSUE THREAD

**Issue by SamuelBrand1** [julia-vscode/TestItemRunner.jl#75]
Hi everyone,

At the moment, there is an option to have `default_imports` `true`/`false` which engages `using MyPackage` (if detected) and `using Test` in every `testitem`. However, I don't see an option to include any other code expressions?

As an example, it would be nice to have a common `rng` for every test item rather than having to add plenty of boiler plate to potentially lots of tests?

**Comment by SamuelBrand1** [comment]
So looking a bit deeper. Would this functionality be covered by test setup? e.g. #71 ?

**Comment by davidanthoff** [comment]
Already tracked by https://github.com/julia-vscode/TestItemRunner.jl/issues/11.
